### ISSUE TITLE
@gf.cell lose the docstring and Pylance formating 

### ISSUE THREAD

**Issue by rgiroud** [gdsfactory/gdsfactory#3106] opened 2024-08-08 09:29 UTC
Hi, 

I've come across something when trying to update from gdsfactory 7 -> 8, which I don't remember happening in 7.*

The decorator @gf.cell doesn't seem to provide the docstring of a Component generating function anymore. The Pylance rendering in VSCode is also impacted.

Picture without the decorator: 
![a](https://github.com/user-attachments/assets/f0e305b9-736b-441e-ac2a-4494da48a4fd)

Picture with the decorator: 
![b](https://github.com/user-attachments/assets/ede7db0c-a52d-479c-9419-7571e3deaa5a)

Is this something fixable? 
I tried a few things (without touching gdsfactory code) like implementing my own decorator using functools.wraps which would apply @gf.cell to the decorated function. This solved the rendering and docstring problem, but rose a cell naming problem.

Thanks

**Comment by sebastian-goeldi** [comment] 2024-08-08 12:20
I think the problem is this:
https://github.com/gdsfactory/gdsfactory/blob/main/gdsfactory/cell.py#L69

This will not create a valid overload signature, therefore the `@overload` will not be able to be resolved by pylance (and probably pretty much any other tool).

**Comment by sebastian-goeldi** [comment] 2024-08-08 18:26
I think this might require a small fix on kfactory's side

**Comment by sebastian-goeldi** [comment] 2024-08-20 13:40
The problem with your approach is that it will disallow any settings on the decorator directly.

Wrt layout_cache: This one will first look into the layout object whether a cell with the targeted name is present and return that instead of executing the function. This is likely because you mix using string with crossections or pass multiple partials etc.

**Comment by joamatab** [comment] 2024-11-15 18:27
Hi Robin,

Is this issue still unresolved? If so, I’ll go ahead and close it. Feel free to reach out if there’s anything else we can assist with.

Best regards,

**Closed by joamatab** 2024-11-15 18:27 UTC
Labels: bug

**Comment by rgiroud** [comment] 2024-11-26 13:18
Hi,

I just updated to gdsfactory to 7.20.0. From what I could observe the @gf.cell decorator still has the same behaviour than described above.

That's not much of an issue tho, I've been doing with my temporary fix in the meantime and if I really needed specific settings from the original decorator, I simply used it instead.
