### ISSUE TITLE
all angle router does not get consistent names

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1708] opened 2023-05-29 17:27 UTC
all angle router does not get consistent names

https://github.com/gdsfactory/gdsfactory/actions/runs/5113997431/jobs/9193803571

@tvt173

**Comment by tvt173** [comment] 2023-05-29 22:45
since when, @joamatab ? do you know what change triggered this?

**Comment by joamatab** [comment] 2023-05-29 23:22
not sure what triggered it, the new difftest catches this issues now as it detects cell name changes that are not at the top level

**Comment by tvt173** [comment] 2023-05-29 23:35
sure, i can take a look... i'd suspect it has to do with floating point numbers passed as part of the transformation... 

in this case, i suppose it would be good if we can get the names to come out the same consistently. but i'm wondering if, in general, we want difftest to be this picky... usually i'm happy if the top-level cell name + XOR is correct, and I would look at a _netlist regression_ for any changes like this to cell names or parameters. i.e. sometimes i might make changes to a cell hierarchy and want to confirm that the layout still comes out the same (XOR-clean) independent of changes to hierarchy/logical structure. i haven't tried the new difftest yet, but I think it would be nice if we are still able to confirm this

**Comment by tvt173** [comment] 2023-06-20 23:05
hi @joamatab , I believe this one was fixed by #1781

**Closed** 2023-06-21 05:46 UTC
Labels: bug
